---
title: "Research projects"
---

\

## Words of Warning: How Illiberal Public Discourse Signals Democratic Decline

I am Chief Investigator of an [Australian Research Council (ARC)](https://www.arc.gov.au/) DECRA project (2026-2028) on how illiberal public discourse signals democratic decline. In this project, I analyze large-scale text data from political speeches, parliamentary debates, and social media to investigate shifting public discourses in several democracies. For further information about this project, see [here.](https://findanexpert.unimelb.edu.au/project/25-3041-words-of-warning--how-illiberal-public-discourse-signals-democratic-decline)

\

## Smart Authoritarianism? Comparing the Internet Strategies of Authoritarian Regimes

I was Principal Investigator and Project Leader of a project on authoritarian Internet strategies (2021-2024), the project was funded by the [German Research Foundation (DFG](https://www.dfg.de/en/index.jsp)) and affiliated with the Institute of Political Science at the Goethe University Frankfurt (Germany), see also [here](https://www.fb03.uni-frankfurt.de/108463498/Schwerpunkt_Methoden_der_Qualitativen_Empirischen_Sozialforschung).
Together with my team and in collaboration with Tina Freyburg (University of St. Gallen) and Lisa Garbe (WZB), we released TOSCO2.0, an updated dataset on ownership
structures of Internet Service Providers (ISPs), more information [here](https://tosco.shinyapps.io/data/).

\

## Neo-Authoritarianism in Europe and the Liberal Democratic Response (AUTHLIB)

I was a participating researcher in the EU Horizon Europe project AUTHLIB.
The project was coordinated by the Central European University (CEU),
other participating institutions were Charles University, German Marshall
Fund, Sciences Po, Scuola Normale Superiore, University of Social
Sciences and Humanities in Warsaw, University of Oxford, and the
University of Vienna. See also the [project's website](http://www.authlib.eu/).

\

## Pandemic Backsliding: Democracy during COVID-19

I was Principal Investigator (together with Anna Lührmann, Amanda B.
Edgell, and Jean Lachapelle) of a project on violations of democratic
standards for emergency responses during the COVID-19 pandemic, the
project was funded by the Swedish Ministry of Foreign Affairs
(2020/2021). For further information about this project, see [here.](https://www.v-dem.net/pandem.html)
